### ISSUE TITLE
chore: change directories to match package name

### ISSUE THREAD

**Issue by BryanPan342** [cdklabs/awscdk-change-analyzer#22]
Currently package directory names are `change-analysis`, `change-analysis-models`, and `web-app`. They should be changed to `cdk-change-analyzer`, `cdk-change-analyzer-models`,  and`cdk-change-analyzer-web-app`.

Honestly not a fan of any of these names, and preferred if we did something like the following:

```
packages
├── @aws-c2a
│   ├── engine
│   ├── models
│   └── web-app
└──  aws-c2a      // CLI stuff
```

I'm also thinking about splitting the parsers in the `@aws-c2a/engine` to something like:
`@aws-c2a/cdk`
`@aws-c2a/cloudformation`

**Comment by rix0rrr** [comment]
This all makes a lot of sense to me. I like your proposed organization, it feels very neat. 

Honestly, to me it's a bit of "potato, potato": since this is not user facing, I don't care a lot about the organization. But I would definitely not stand in your way if you want to go ahead and clean it up.
